config/routes.rb
Pint::Application.routes.draw do

  resources :age_categories

  resources :books

  resources :answers

  resources :questions

  resources :quizzs

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :words

  resources :stories

  devise_for :users

  root 'pages#landing'
  get 'mystories' => 'stories#mystories'

  get 'worddef' => 'words#get_def'
  get 'dashboard' => 'users#dashboard'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/age_category.rb
class AgeCategory < ActiveRecord::Base
  has_many :books
  has_many :stories
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_many :panels
  has_many :users, through: :panels
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_many :stories
  belongs_to :age_category

  validates :title, presence: true
  validates :image, presence: true
end

app/models/dictionnary.rb
#WORD-STORIES
class Dictionnary < ActiveRecord::Base
  validates :story_id, presence: true
  validates :word_id, presence: true

  belongs_to :story
  belongs_to :word
end

app/models/library.rb
class Library < ActiveRecord::Base
  validates :story_id, presence: true
  validates :user_id, presence: true

  belongs_to :story
  belongs_to :user
end

app/models/panel.rb
#USER-ANSWERS
class Panel < ActiveRecord::Base
  validates :user_id, presence: true
  validates :answer_id, presence: true

  belongs_to :user
  belongs_to :answer
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :story
  has_many :answers
end

app/models/story.rb
class Story < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  validates :description, presence: true
  validates :image, presence: true
  validates :key, presence: true

  belongs_to :book
  #USER-STORY
  has_many :libraries
  has_many :users, through: :libraries
  #WORD-STORIES
  has_many :dictionnaries
  has_many :words, through: :dictionnaries

  has_many :questions
  belongs_to :age_category


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true

  #USER-STORY
  has_many :libraries
  has_many :stories, through: :libraries
  
  #USER-WORDS
  has_many :vocabularies
  has_many :words, through: :vocabularies
  
  #USER-ANSWERS
  has_many :panels
  has_many :answers, through: :panels

  
end

app/models/vocabulary.rb
#USER-WORD
class Vocabulary < ActiveRecord::Base
  validates :user_id, presence: true
  validates :word_id, presence: true

  belongs_to :user
  belongs_to :word
end

app/models/word.rb
 class Word < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  #USER-WORDS
  has_many :vocabularies
  has_many :users, through: :vocabularies
  
  #WORD-STORIES
  has_many :dictionnaries
  has_many :stories, through: :dictionnaries

end

app/controllers/age_categories_controller.rb
class AgeCategoriesController < InheritedResources::Base
end

app/helpers/age_categories_helper.rb
module AgeCategoriesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def words_in_book(book)
    @S = 0
    book.stories.each do |story|
      @S += story.words.count
    end
    @S
  end
end

app/helpers/content_helper.rb
module ContentHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzs_helper.rb
module QuizzsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/age_categories/_form.html.erb
<%= form_for(@age_category) do |f| %>
  <% if @age_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@age_category.errors.count, "error") %> prohibited this age_category from being saved:</h2>

      <ul>
      <% @age_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="">
    <%= f.submit %>
  </div>
<% end %>

app/views/age_categories/edit.html.erb
<h1>Editing age_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @age_category %> |
<%= link_to 'Back', age_categories_path %>

app/views/age_categories/index.html.erb
<h1>Listing age_categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @age_categories.each do |age_category| %>
      <tr>
        <td><%= age_category.name %></td>
        <td><%= link_to 'Show', age_category %></td>
        <td><%= link_to 'Edit', edit_age_category_path(age_category) %></td>
        <td><%= link_to 'Destroy', age_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Age category', new_age_category_path %>

app/views/age_categories/new.html.erb
<h1>New age_category</h1>

<%= render 'form' %>

<%= link_to 'Back', age_categories_path %>

app/views/age_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @age_category.name %>
</p>

<%= link_to 'Edit', edit_age_category_path(@age_category) %> |
<%= link_to 'Back', age_categories_path %>