config/routes.rb
Pint::Application.routes.draw do

  resources :age_categories

  resources :books

  resources :answers

  resources :questions

  resources :quizzs

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :words

  resources :stories

  devise_for :users

  root 'pages#landing'
  get 'mystories' => 'stories#mystories'

  get 'worddef' => 'words#get_def'
  get 'dashboard' => 'users#dashboard'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/age_category.rb
class AgeCategory < ActiveRecord::Base
  has_many :books
  has_many :stories
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_many :panels
  has_many :users, through: :panels
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_many :stories
  belongs_to :age_category

  validates :title, presence: true
  validates :image, presence: true
end

app/models/dictionnary.rb
#WORD-STORIES
class Dictionnary < ActiveRecord::Base
  validates :story_id, presence: true
  validates :word_id, presence: true

  belongs_to :story
  belongs_to :word
end

app/models/library.rb
class Library < ActiveRecord::Base
  validates :story_id, presence: true
  validates :user_id, presence: true

  belongs_to :story
  belongs_to :user
end

app/models/panel.rb
#USER-ANSWERS
class Panel < ActiveRecord::Base
  validates :user_id, presence: true
  validates :answer_id, presence: true

  belongs_to :user
  belongs_to :answer
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :story
  has_many :answers
end

app/models/story.rb
class Story < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  validates :description, presence: true
  validates :image, presence: true
  validates :key, presence: true

  belongs_to :book
  #USER-STORY
  has_many :libraries
  has_many :users, through: :libraries
  #WORD-STORIES
  has_many :dictionnaries
  has_many :words, through: :dictionnaries

  has_many :questions
  belongs_to :age_category


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true

  #USER-STORY
  has_many :libraries
  has_many :stories, through: :libraries
  
  #USER-WORDS
  has_many :vocabularies
  has_many :words, through: :vocabularies
  
  #USER-ANSWERS
  has_many :panels
  has_many :answers, through: :panels

  
end

app/models/vocabulary.rb
#USER-WORD
class Vocabulary < ActiveRecord::Base
  validates :user_id, presence: true
  validates :word_id, presence: true

  belongs_to :user
  belongs_to :word
end

app/models/word.rb
 class Word < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  #USER-WORDS
  has_many :vocabularies
  has_many :users, through: :vocabularies
  
  #WORD-STORIES
  has_many :dictionnaries
  has_many :stories, through: :dictionnaries

end

app/controllers/books_controller.rb
class BooksController < InheritedResources::Base
  before_action :set_book, only: [:show]
  before_action :paginate, only: [:index, :main, :show]

  def index
    @books = Book.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def paginate
      @books = Book.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  def index
    @words = Word.all
  end

  def show
  end

  def new
    @word = Word.new
  end

  def edit
  end

  def create
    @word = Word.new(word_params)
    if @word.save
      redirect_to @word, notice: 'Word was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @word.update(word_params)
      redirect_to @word, notice: 'Word was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @word.destroy
    redirect_to words_url
  end

  def get_def
    puts params[:word]
    @word = Word.find_by name:(params[:word])
    respond_to do |format|
      format.html { render :layout => false }
    end
  end

  private
    def set_word
      @word = Word.find(params[:id])
    end

    def word_params
      params.require(:word).permit(:name, :definition, :grammar)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def words_in_book(book)
    @S = 0
    book.stories.each do |story|
      @S += story.words.count
    end
    @S
  end
end

app/helpers/content_helper.rb
module ContentHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzs_helper.rb
module QuizzsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/get_def.html.erb
<p> <%= @word.definition %></p>

app/views/words/index.html.erb
<main>
  <div class="color-scheme--lightgrey">
    <div class="fit-fixed grid-row">
      <div class="grid-col-12 margin-top--3 margin-bottom--3 grid-col--align-center">
        <h3 class="margin-bottom--2">Révise et gagne des points !</h3>
        <div class="grid-row">
          <div class="grid-col-4 grid-col--no-padding">
            <article class="card card--link grid-col-4 color-scheme--white grid-row grid-col--no-padding  " >
              <div class="grid-col-12 grid-col--align-center grid-col--no-padding grid-col--no-margin card-header ">
                  <h1 class="margin-top--3">
                    <span class="cc-symbol icon--large">web</span>
                  </h1>
              </div>
              <div class="grid-col-12 grid-col--align-center">
                <h3 class="text--ellipsis">Dictionnaire</h3>
                  <p class="content-card__description">
                    Relis les mots les plus difficiles et apprends-en de nouveaux en faisant nos quizzs de la mort !
                  </p>
                <br>
                <%= "#{current_user.words.where("definition IS NOT NULL").count} mots difficiles" %>
                <div class="last-progress">
                    <small class="text--ellipsis">&nbsp;</small>
                </div>
              </div>
              <div class="grid-col-12 grid-col--align-center grid-col--no-margin grid-col--no-padding">
                <hr class="no-margin">
              </div>
              <a href="/mydifficultwords" class="link--target"></a>
            </article>
          </div>
          <div class="grid-col-4 grid-col--no-padding">
            <article class="card card--link grid-col-4 color-scheme--white grid-row grid-col--no-padding  " >
              <div class="grid-col-12 grid-col--align-center grid-col--no-padding grid-col--no-margin card-header ">
                <h1 class="margin-top--3">
                  <span class="cc-symbol icon--large">apis</span>
                </h1>
              </div>
              <div class="grid-col-12 grid-col--align-center">
                <h3 class="text--ellipsis">Bescherelle</h3>
                <p class="content-card__description">
                  Conjugue tes verbes et gagne des points !
                </p>
                <br>
                <%= "#{current_user.words.where(grammar: :verb).count} verbes conjugués lus" %>
                <div class="last-progress">
                    <small class="text--ellipsis">&nbsp;</small>
                </div>
              </div>
              <div class="grid-col-12 grid-col--align-center grid-col--no-margin grid-col--no-padding">
                <hr class="no-margin">
              </div>
              <a href="/mybescherelle" class="link--target"></a>
            </article>
          </div>
          <div class="grid-col-4 grid-col--no-padding">
            <article class="card card--link grid-col-4 color-scheme--white grid-row grid-col--no-padding  " >
              <div class="grid-col-12 grid-col--align-center grid-col--no-padding grid-col--no-margin card-header ">
                <h1 class="margin-top--3">
                  <span class="cc-symbol icon--large">web</span>

                </h1>
              </div>
              <div class="grid-col-12 grid-col--align-center">
                <h3 class="text--ellipsis">Tous tes mots</h3>
                <p class="content-card__description">
                  Montre tous tes mots à tes parents ! Les adultes en connaissent 7,000 ! Et toi, combien en as-tu lus ici ?
                </p>
                <br>
                <%= "#{current_user.words.count} mots" %>
                <div class="last-progress">
                    <small class="text--ellipsis">&nbsp;</small>
                </div>
              </div>
              <div class="grid-col-12 grid-col--align-center grid-col--no-margin grid-col--no-padding">
                <hr class="no-margin">
              </div>
              <a href="/mywords" class="link--target"></a>
            </article>
          </div>          
        </div>
      </div>
    </div>
  </div>  
</main>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @word.name %>
</p>

<p>
  <strong>Definition:</strong>
  <%= @word.definition %>
</p>

<p>
  <strong>User:</strong>
  <%= @word.user %>
</p>

<%= link_to 'Back', words_path %>